FROM rockylinux:9

COPY setup-system.sh /tmp/setup-system.sh
RUN /tmp/setup-system.sh && rm -f /tmp/setup-system.sh
COPY setup-z-push.sh /tmp/setup-z-push.sh
RUN /tmp/setup-z-push.sh && rm -f /tmp/setup-z-push.sh
COPY rootfs/ /
ENTRYPOINT ["/sbin/init"]